apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dil-deploy
  name: dil-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dil-deploy
  template:
    metadata:
      labels:
        app: dil-deploy
    spec:
      containers:
      - image: baskarmaniax/takin:latest
        name: pet
