apiVersion: v1
kind: Service
metadata:
  labels:
    app: pet-deploy
  name: dil-svc
  #namespace: pet
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dil-deploy
  type: NodePort
